### ISSUE TITLE
Visual Parking Lot

### ISSUE THREAD

**Issue by dkgroot** [chan-sccp/chan-sccp#139]
Show a list of calls in the parking lot (By CallerId), which can be retrieved.

Possibly requires builing xmlserver (Large lists on 7960 don't work, wenn pushed)

Depending on xmlservice

**Comment by dkgroot** [comment]
Update  f33fbe1
https://github.com/dkgroot/chan-sccp-b/tree/feature/visualpark

button = feature, parking, ParkingLot, default
following "button = feature, <buttonname>, <FeatureId>, <parkinglot-name>

**Comment by dkgroot** [comment]
James Farell and David Andrzejewski are currently testing this new feature in the development branch.

**Comment by dandrzejewski** [comment]
If the device restarts when there is a call in the parking lot, the button does not flash amber after the phone boots back up.  If I pick the call up and park it again, it's there.

**Comment by dkgroot** [comment]
@dandrzejewski I did try to implement that, but it made the source look ugly and convoluted, so i decided against it. 

Explanation: The module is listening for AMI event, so it does not query or poll the parkinglot. There is no asterisk function to call from the chan-sccp side to find out the parkinglot status. To implement this anyway, we would have to query AMI and parse the results. Which would require two parsers(one event based and one ami parkinglot query), which is a little ugly. 

Can we live without it, or do you deem it absolutely necessary ?

**Comment by dkgroot** [comment]
Implemented following Visual Park Button handling:
* If we have an active call -> pressing the park feature key, will park that call
* If we are not on an active call:
   * If there is 0 parked calls: Display Status Message, "No parked calls'
   * If there is 1 parked call: Unpark that call immediatly
   * If there is more than 1 parked call: display the visual parking lot representation.

**Comment by dkgroot** [comment]
@jamesmz & @dandrzejewski 
Have you guys been able to run a couple of tests using the latest revisions. I think all the open issues have been resolved.

**Comment by jamesmz** [comment]
Yes, all seems OK my end.

**Comment by dkgroot** [comment]
@jamesmz: Thanks for the update !

Just added optional: 'RetrieveSingle' flag as per @dandrzejewski request.
So new definition
~~~~
button = feature, parking, ParkingLot, default
button = feature, parking, ParkingLot, default, retrieveSingle
following "button = feature, <buttonname>,<featureid>,<parkinglot-name> [,retrrieveSingle]
~~~~

@jamesmz So in your case you would have to add 'retrieveSingle' at the end of the button line.

Once this last change has been tested, we should make the new feature public and enabled by default, i think.

**Comment by jamesmz** [comment]
I can confirm that it is working as intended both with and without the retrieveSingle flag.

I'm happy to do the Wiki page. Leave it with me.

**Comment by dkgroot** [comment]
@jamesmz Thanks for testing and confirming that everything works as expected.
Please check with @dandrzejewski, we was doing some work on the wiki over the weekend as well.

**Comment by dandrzejewski** [comment]
Here's an issue. If I reboot a phone (**#** from the menu), when it comes back up, the parking lot button is not flashing and the icon is the white circle, not the black circle. This is on my 7971.

**Comment by dkgroot** [comment]
@dandrzejewski : This is similar to the issue when unloading/load the sccp module, whereby we would not know that there are any parked calls. This one is solvable how ever. Will look into it, to see what i can do.

**Comment by dandrzejewski** [comment]
Cool.  Yeah I'm wondering if there's some call you can make when a phone registers that says "hey Asterisk, any parked calls right now?"

FWIW, when I press the button, it works correctly and shows the parked call.

**Comment by dkgroot** [comment]
Luckly we are caching the park state, inside sccp_featureParkingLot, so that's not an issue, i just need to check when starting
This is not the same as the issue with the module reload, where we have missed all the state events... I would have to add a whole chunk of code (and work) to make that possible, which i think is a little over the top. Call it an edge case, which we don't support :-)

**Comment by dkgroot** [comment]
@dandrzejewski created: https://github.com/chan-sccp/chan-sccp/wiki/Visual-Parking-Lot
@jamesmz if you would like you can add/update/extend any of the information on this wiki page.

**Comment by dkgroot** [comment]
@jamesmz I have mainlined the visual parkinglot implementaton now. So you don't need '--enable-experimental-mode' any more.

**Comment by jamesmz** [comment]
It looks like the voicemail light coming on when a call is parked has stopped working on 7940/60. Would it be possible to get that back? We found it quite useful.

**Comment by dkgroot** [comment]
Done :-)

**Comment by jamesmz** [comment]
All working OK, thank you :)

**Comment by dkgroot** [comment]
Happy that we finished this brand new feature :-) Closing the issue.
