### ISSUE TITLE
Update Wiki Pages

### ISSUE THREAD

**Issue by dkgroot** [chan-sccp/chan-sccp#290]
After the migration from sourceforge some of the links need to be update.
Wiki content is a little outdated at some places.
New Wiki content is still required

**Comment by dkgroot** [comment]
Work in progress. Could use some help !

**Comment by marcelloceschia** [comment]
@dkgroot Hilfe, bei was bzw wie willst Du es aufteilen?

**Comment by dkgroot** [comment]
I think we are mostly done :-) 
Fixed the FreePBX Section
@dandrzejewski is going to have another look, to see if anything is missing / requires updating etc... Thanks David.

**Comment by dkgroot** [comment]
Done:
* Moved FreePBX related pages around and change the Menu order. 

Todo:
* Still need to merge the Setup FreePBX and the FreePBX page content into one (don't know which is better/newer).
* I think we need more screen captures (color: 7970 and 7960: if necessary)
* Setting up /etc/asterisk/logger.conf 
* More feature coverage
