### ISSUE TITLE
Pickup call from speeddial line using orange button

### ISSUE THREAD

**Issue by drtmk** [chan-sccp/chan-sccp#296]
Is there any way to pickup incomming call for speeddial line using blinking orange button and not by bottom keys?
Currently when I press this button, I'm making a new call to the extension associated with speeddial line.

Asterisk 13.8.2
chan_sccp 4.3.2
Two cisco 7942G phones

**Comment by dkgroot** [comment]
That can be done using a little dialplan logic.
Have a look at this [wiki page]
(https://github.com/chan-sccp/chan-sccp/wiki/Monitor and Pickup Incoming Calls via Speeddial Using Custom Devstate)
(solution provided by Marcello)

**Comment by dkgroot** [comment]
Issue closed
