### ISSUE TITLE
Visual parking lot menu comes back on screen after exiting and un-parking elsewhere

### ISSUE THREAD

**Issue by jamesmz** [chan-sccp/chan-sccp#300]
Using latest commit in development branch and 7960 phones.

If two calls are parked using separate phones on the system, then on a third phone the visual parking lot menu is displayed and exited, when un-parking a call elsewhere the menu returns by itself on the third phone.

**Comment by dkgroot** [comment]
Related: #139

**Comment by dkgroot** [comment]
Note: Requires 'sccp debug core, pbx, channel, newcode, action' during testing, to show all the interaction, we are now handling the menu interaction via sccp_action.c: handle_device_to_user.

**Comment by jamesmz** [comment]
Seems to be working correctly in the latest release, thank you.

**Comment by dkgroot** [comment]
Ok, nice !
Closing this issue (You can re-open, report a new issue or add a comment on #139).
