### ISSUE TITLE
[Regression] Missing AMI event DeviceStateChange on RINGING

### ISSUE THREAD

**Issue by pnlarsson** [chan-sccp/chan-sccp#306]
This event is in 4.2 but not in master och develop branch:

Event: DeviceStateChange
Privilege: call,all
SystemName: s50
Device: SCCP/519
State: RINGING

**asterisk version:** 13.9

./configure --enable-debug --disable-park --disable-dirtrfr --disable-pickup --with-astmoddir=/usr/local/ngcore/service/pbx/usr/lib/asterisk/modules --enable-experiment-mode --no-create --no-recursion

No change if configured with or without --enable-experiment-mode

**Comment by dkgroot** [comment]
Is this directly related to issue #307 ?

**Comment by pnlarsson** [comment]
Kind of, we used the DeviceStateChange as a band aid fix to get the line state ringing. So if #307 works this is not needed (for us).

**Comment by dkgroot** [comment]
Even better ! Thanks for the update ! Closing this issue as well !
