### ISSUE TITLE
PBX state RINGING is missing

### ISSUE THREAD

**Issue by pnlarsson** [chan-sccp/chan-sccp#307]
The PBX does not know that the sccp device/line is ringing:
```
   -- Called SCCP/519
    -- SCCP/519-00000001 is ringing
 uc50*CLI> sccp show channels 

 +--- Channels ----------------------------------------------------------------------------------------------------------------------------------------------+
 | ID    Name                      LineName   DeviceName       NumCalled  PBX State  SCCP State ReadCodec  WriteCodec RTPPeer                Direct DTMFmode |
 + ===== ========================= ========== ================ ========== ========== ========== ========== ========== ====================== ====== ======== +
 | 1     SCCP/519-00000001         519        SCCP                        Down       RINGING    alaw/64k   alaw/64k                          no     RFC2833  | 
 +-----------------------------------------------------------------------------------------------------------------------------------------------------------+
```

And it wont send the ExtensionStatus Rining AMI event

This has been the same for as long as I used chan_sccp.

A fix (not recomended) is to uncomment the 
```
//                      iPbx.set_callstate(c, AST_STATE_RINGING);                                               /*!\todo thats not the right place to update pbx state */
```

line in src/sccp_indicate.c

**asterisk version:** 13.9

**Comment by dkgroot** [comment]
Can you check again using this revision, to see if it fixes the issue on your system as well ?

**Comment by pnlarsson** [comment]
Tested latest develop bransh and it's now working as it should. Thanks

**Comment by dkgroot** [comment]
Nice, We finally fixed this one, thanks for the update. 

Closing this issue !

**Comment by dkgroot** [comment]
Reverting related changes back to af666b3 for now. Reopening issue

**Comment by marcelloceschia** [comment]
I've check this @ develop branch and it looks like this issue is fixed.
@pnlarsson can you confirm this?

**Comment by pnlarsson** [comment]
Yepp, using revert_session_handler I get:

Event: DeviceStateChange
Privilege: call,all
SystemName: s1
Device: SCCP/519
State: RINGING

So I will close this issue.

**Comment by marcelloceschia** [comment]
Is it possible to check this for develop branch too?
Otherwise I have to merge this changes back to develop branch.

**Comment by pnlarsson** [comment]
With develop branch: 

Event: ExtensionStatus
Privilege: call,all
SystemName: s1
Exten: 519
Context: company_4_hints
Hint: SCCP/519
Status: 8
StatusText: Ringing

Event: DeviceStateChange
Privilege: call,all
SystemName: s1
Device: SCCP/519
State: RINGING

So I'm happy :-)

**Comment by marcelloceschia** [comment]
Thanks you for this positive feedback :)
