### ISSUE TITLE
SCCP: Unknown param at device:15:redial_menu='yes'

### ISSUE THREAD

**Issue by bsdkllr** [chan-sccp/chan-sccp#320]
unable to enable redial_menu=yes  even with --enable-experimental-mode set when configuring

shows error SCCP: Unknown param at device:15:redial_menu='yes'

**Comment by marcelloceschia** [comment]
Rename redial_menu to useRedialMenu

**Comment by bsdkllr** [comment]
thank you that fixed it

**Comment by marcelloceschia** [comment]
You can check src/sccp_config_entries.hh for all config entries

**Comment by dkgroot** [comment]
Remedial menu param requires --enable-experimental-mode during configure, to be available.

@marcello: maybe we schould remove the experimental mode for remedial menu.

On June 12, 2016 5:08:06 PM CEST, Marcello Ceschia <notifications@github.com> wrote:
>You can check src/sccp_config_entries.hh for all config entries 
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/chan-sccp/chan-sccp/issues/320#issuecomment-225441122

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by marcelloceschia** [comment]
@dkgroot I think experimental-mode is not required for useRedialMenu

**Comment by dkgroot** [comment]
Aha ok. Wasnt sure.

On June 15, 2016 10:27:24 AM CEST, Marcello Ceschia <notifications@github.com> wrote:
>@dkgroot I think experimental-mode is not required for useRedialMenu
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/chan-sccp/chan-sccp/issues/320#issuecomment-226121568

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
