### ISSUE TITLE
Compilation crashes with option --with-hash-size

### ISSUE THREAD

**Issue by jozzus** [chan-sccp/chan-sccp#375]
Packege can't be compiled with option --with-hash-size

**Reproduction Steps:**

1. Download from Development brance (git clone https://github.com/chan-sccp/chan-sccp chan-sccp_develop)
2. Configure with options (./configure --enable-conference --enable-distributed-devicestate --with-astmoddir=/usr/lib64/asterisk/modules/ --enable-advanced-functions --with-hash-size)
3. make

**Expected behavior:**

The packege shuld be compiled

**Observed behavior:**

Compilation exitedwith Error

**Screenshots**

In file included from sccp_refcount.c:40:0:
config.h:689:25: error: ‘yes’ undeclared here (not in a function)
 #define SCCP_HASH_PRIME yes
                         ^
sccp_refcount.c:111:12: note: in expansion of macro ‘SCCP_HASH_PRIME’
 } *objects[SCCP_HASH_PRIME];           //!< objects hash table
            ^
In file included from common.h:46:0,
                 from sccp_refcount.c:41:
sccp_refcount.c: In function ‘sccp_refcount_destroy’:
sccp_dllists.h:97:20: error: invalid type argument of ‘->’ (have ‘int’)
  typeof(__list_head->first) __list_next;        \
                    ^
sccp_dllists.h:107:41: note: in expansion of macro ‘SCCP_LIST_TRAVERSE_SAFE_BEGIN’
 #define SCCP_RWLIST_TRAVERSE_SAFE_BEGIN SCCP_LIST_TRAVERSE_SAFE_BEGIN
                                         ^
sccp_refcount.c:146:4: note: in expansion of macro ‘SCCP_RWLIST_TRAVERSE_SAFE_BEGIN’
    SCCP_RWLIST_TRAVERSE_SAFE_BEGIN(&(objects[hash]->refCountedObjects), obj, list) {
    ^
sccp_dllists.h:98:20: error: invalid type argument of ‘->’ (have ‘int’)
  typeof(__list_head->first) __list_prev = NULL;       \
                    ^
sccp_dllists.h:107:41: note: in expansion of macro ‘SCCP_LIST_TRAVERSE_SAFE_BEGIN’
 #define SCCP_RWLIST_TRAVERSE_SAFE_BEGIN SCCP_LIST_TRAVERSE_SAFE_BEGIN
                                         ^
sccp_refcount.c:146:4: note: in expansion of macro ‘SCCP_RWLIST_TRAVERSE_SAFE_BEGIN’
    SCCP_RWLIST_TRAVERSE_SAFE_BEGIN(&(objects[hash]->refCountedObjects), obj, list) {
    ^
sccp_dllists.h:99:20: error: invalid type argument of ‘->’ (have ‘int’)
  typeof(__list_head->first) __new_prev = NULL;       \
                    ^
sccp_dllists.h:107:41: note: in expansion of macro ‘SCCP_LIST_TRAVERSE_SAFE_BEGIN’
 #define SCCP_RWLIST_TRAVERSE_SAFE_BEGIN SCCP_LIST_TRAVERSE_SAFE_BEGIN
                                         ^
sccp_refcount.c:146:4: note: in expansion of macro ‘SCCP_RWLIST_TRAVERSE_SAFE_BEGIN’
    SCCP_RWLIST_TRAVERSE_SAFE_BEGIN(&(objects[hash]->refCountedObjects), obj, list) {
    ^
sccp_dllists.h:100:26: error: invalid type argument of ‘->’ (have ‘int’)
  for ((var) = __list_head->first, __new_prev = (var),      \
                          ^
sccp_dllists.h:107:41: note: in expansion of macro ‘SCCP_LIST_TRAVERSE_SAFE_BEGIN’
 #define SCCP_RWLIST_TRAVERSE_SAFE_BEGIN SCCP_LIST_TRAVERSE_SAFE_BEGIN
                                         ^
sccp_refcount.c:146:4: note: in expansion of macro ‘SCCP_RWLIST_TRAVERSE_SAFE_BEGIN’
    SCCP_RWLIST_TRAVERSE_SAFE_BEGIN(&(objects[hash]->refCountedObjects), obj, list) {
    ^
sccp_dllists.h:100:46: warning: assignment makes integer from pointer without a cast [enabled by default]
  for ((var) = __list_head->first, __new_prev = (var),      \
                                              ^
sccp_dllists.h:107:41: note: in expansion of macro ‘SCCP_LIST_TRAVERSE_SAFE_BEGIN’
 #define SCCP_RWLIST_TRAVERSE_SAFE_BEGIN SCCP_LIST_TRAVERSE_SAFE_BEGIN
                                         ^
sccp_refcount.c:146:4: note: in expansion of macro ‘SCCP_RWLIST_TRAVERSE_SAFE_BEGIN’
    SCCP_RWLIST_TRAVERSE_SAFE_BEGIN(&(objects[hash]->refCountedObjects), obj, list) {
    ^
sccp_dllists.h:100:33: warning: left-hand operand of comma expression has no effect [-Wunused-value]
  for ((var) = __list_head->first, __new_prev = (var),      \
                                 ^
sccp_dllists.h:107:41: note: in expansion of macro ‘SCCP_LIST_TRAVERSE_SAFE_BEGIN’
 #define SCCP_RWLIST_TRAVERSE_SAFE_BEGIN SCCP_LIST_TRAVERSE_SAFE_BEGIN
                                         ^
sccp_refcount.c:146:4: note: in expansion of macro ‘SCCP_RWLIST_TRAVERSE_SAFE_BEGIN’
    SCCP_RWLIST_TRAVERSE_SAFE_BEGIN(&(objects[hash]->refCountedObjects), obj, list) {
    ^
sccp_dllists.h:101:20: warning: assignment makes integer from pointer without a cast [enabled by default]
        __list_next = (var) ? (var)->field.next : NULL;      \
                    ^
sccp_dllists.h:107:41: note: in expansion of macro ‘SCCP_LIST_TRAVERSE_SAFE_BEGIN’
 #define SCCP_RWLIST_TRAVERSE_SAFE_BEGIN SCCP_LIST_TRAVERSE_SAFE_BEGIN
                                         ^
sccp_refcount.c:146:4: note: in expansion of macro ‘SCCP_RWLIST_TRAVERSE_SAFE_BEGIN’
    SCCP_RWLIST_TRAVERSE_SAFE_BEGIN(&(objects[hash]->refCountedObjects), obj, list) {
    ^
sccp_dllists.h:100:33: warning: value computed is not used [-Wunused-value]
  for ((var) = __list_head->first, __new_prev = (var),      \
                                 ^
sccp_dllists.h:107:41: note: in expansion of macro ‘SCCP_LIST_TRAVERSE_SAFE_BEGIN’
 #define SCCP_RWLIST_TRAVERSE_SAFE_BEGIN SCCP_LIST_TRAVERSE_SAFE_BEGIN
                                         ^
sccp_refcount.c:146:4: note: in expansion of macro ‘SCCP_RWLIST_TRAVERSE_SAFE_BEGIN’
    SCCP_RWLIST_TRAVERSE_SAFE_BEGIN(&(objects[hash]->refCountedObjects), obj, list) {
    ^
sccp_dllists.h:103:39: warning: assignment makes pointer from integer without a cast [enabled by default]
       __list_prev = __new_prev, (var) = __list_next,      \
                                       ^
sccp_dllists.h:107:41: note: in expansion of macro ‘SCCP_LIST_TRAVERSE_SAFE_BEGIN’
 #define SCCP_RWLIST_TRAVERSE_SAFE_BEGIN SCCP_LIST_TRAVERSE_SAFE_BEGIN
                                         ^
sccp_refcount.c:146:4: note: in expansion of macro ‘SCCP_RWLIST_TRAVERSE_SAFE_BEGIN’
    SCCP_RWLIST_TRAVERSE_SAFE_BEGIN(&(objects[hash]->refCountedObjects), obj, list) {
    ^
sccp_dllists.h:104:18: warning: assignment makes integer from pointer without a cast [enabled by default]
       __new_prev = (var),         \
                  ^
sccp_dllists.h:107:41: note: in expansion of macro ‘SCCP_LIST_TRAVERSE_SAFE_BEGIN’
 #define SCCP_RWLIST_TRAVERSE_SAFE_BEGIN SCCP_LIST_TRAVERSE_SAFE_BEGIN
                                         ^
sccp_refcount.c:146:4: note: in expansion of macro ‘SCCP_RWLIST_TRAVERSE_SAFE_BEGIN’
    SCCP_RWLIST_TRAVERSE_SAFE_BEGIN(&(objects[hash]->refCountedObjects), obj, list) {
    ^
sccp_dllists.h:105:19: warning: assignment makes integer from pointer without a cast [enabled by default]
       __list_next = (var) ? (var)->field.next : NULL      \
                   ^
sccp_dllists.h:107:41: note: in expansion of macro ‘SCCP_LIST_TRAVERSE_SAFE_BEGIN’
 #define SCCP_RWLIST_TRAVERSE_SAFE_BEGIN SCCP_LIST_TRAVERSE_SAFE_BEGIN
                                         ^
sccp_refcount.c:146:4: note: in expansion of macro ‘SCCP_RWLIST_TRAVERSE_SAFE_BEGIN’
    SCCP_RWLIST_TRAVERSE_SAFE_BEGIN(&(objects[hash]->refCountedObjects), obj, list) {
    ^
sccp_dllists.h:111:12: error: invalid type argument of ‘->’ (have ‘int’)
  __new_prev->field.next = NULL;         \
            ^
sccp_dllists.h:130:36: note: in expansion of macro ‘SCCP_LIST_REMOVE_CURRENT’
 #define SCCP_RWLIST_REMOVE_CURRENT SCCP_LIST_REMOVE_CURRENT
                                    ^
sccp_refcount.c:149:6: note: in expansion of macro ‘SCCP_RWLIST_REMOVE_CURRENT’
      SCCP_RWLIST_REMOVE_CURRENT(list);
      ^
sccp_dllists.h:112:12: error: invalid type argument of ‘->’ (have ‘int’)
  __new_prev->field.prev = NULL;         \
            ^
sccp_dllists.h:130:36: note: in expansion of macro ‘SCCP_LIST_REMOVE_CURRENT’
 #define SCCP_RWLIST_REMOVE_CURRENT SCCP_LIST_REMOVE_CURRENT
                                    ^
sccp_refcount.c:149:6: note: in expansion of macro ‘SCCP_RWLIST_REMOVE_CURRENT’
      SCCP_RWLIST_REMOVE_CURRENT(list);
      ^
sccp_dllists.h:116:14: warning: assignment makes integer from pointer without a cast [enabled by default]
   __new_prev = NULL;         \
              ^
sccp_dllists.h:130:36: note: in expansion of macro ‘SCCP_LIST_REMOVE_CURRENT’
 #define SCCP_RWLIST_REMOVE_CURRENT SCCP_LIST_REMOVE_CURRENT
                                    ^
sccp_refcount.c:149:6: note: in expansion of macro ‘SCCP_RWLIST_REMOVE_CURRENT’
      SCCP_RWLIST_REMOVE_CURRENT(list);
      ^
sccp_dllists.h:119:15: error: invalid type argument of ‘->’ (have ‘int’)
    __list_next->field.prev = __list_prev;      \
               ^
sccp_dllists.h:130:36: note: in expansion of macro ‘SCCP_LIST_REMOVE_CURRENT’
 #define SCCP_RWLIST_REMOVE_CURRENT SCCP_LIST_REMOVE_CURRENT
                                    ^
sccp_refcount.c:149:6: note: in expansion of macro ‘SCCP_RWLIST_REMOVE_CURRENT’
      SCCP_RWLIST_REMOVE_CURRENT(list);
      ^
sccp_dllists.h:120:14: error: invalid type argument of ‘->’ (have ‘int’)
   __list_prev->field.next = __list_next;       \
              ^
sccp_dllists.h:130:36: note: in expansion of macro ‘SCCP_LIST_REMOVE_CURRENT’
 #define SCCP_RWLIST_REMOVE_CURRENT SCCP_LIST_REMOVE_CURRENT
                                    ^
sccp_refcount.c:149:6: note: in expansion of macro ‘SCCP_RWLIST_REMOVE_CURRENT’
      SCCP_RWLIST_REMOVE_CURRENT(list);
      ^
sccp_dllists.h:122:14: error: invalid type argument of ‘->’ (have ‘int’)
   __list_head->first = __list_next;       \
              ^
sccp_dllists.h:130:36: note: in expansion of macro ‘SCCP_LIST_REMOVE_CURRENT’
 #define SCCP_RWLIST_REMOVE_CURRENT SCCP_LIST_REMOVE_CURRENT
                                    ^
sccp_refcount.c:149:6: note: in expansion of macro ‘SCCP_RWLIST_REMOVE_CURRENT’
      SCCP_RWLIST_REMOVE_CURRENT(list);
      ^
sccp_dllists.h:124:15: error: invalid type argument of ‘->’ (have ‘int’)
    __list_next->field.prev = NULL;       \
               ^
sccp_dllists.h:130:36: note: in expansion of macro ‘SCCP_LIST_REMOVE_CURRENT’
 #define SCCP_RWLIST_REMOVE_CURRENT SCCP_LIST_REMOVE_CURRENT
                                    ^
sccp_refcount.c:149:6: note: in expansion of macro ‘SCCP_RWLIST_REMOVE_CURRENT’
      SCCP_RWLIST_REMOVE_CURRENT(list);
      ^
sccp_dllists.h:127:14: error: invalid type argument of ‘->’ (have ‘int’)
   __list_head->last = __list_prev;        \
              ^
sccp_dllists.h:130:36: note: in expansion of macro ‘SCCP_LIST_REMOVE_CURRENT’
 #define SCCP_RWLIST_REMOVE_CURRENT SCCP_LIST_REMOVE_CURRENT
                                    ^
sccp_refcount.c:149:6: note: in expansion of macro ‘SCCP_RWLIST_REMOVE_CURRENT’
      SCCP_RWLIST_REMOVE_CURRENT(list);
      ^
sccp_dllists.h:128:13: error: invalid type argument of ‘->’ (have ‘int’)
  __list_head->size--;           \
             ^
sccp_dllists.h:130:36: note: in expansion of macro ‘SCCP_LIST_REMOVE_CURRENT’
 #define SCCP_RWLIST_REMOVE_CURRENT SCCP_LIST_REMOVE_CURRENT
                                    ^
sccp_refcount.c:149:6: note: in expansion of macro ‘SCCP_RWLIST_REMOVE_CURRENT’
      SCCP_RWLIST_REMOVE_CURRENT(list);
      ^
sccp_refcount.c: In function ‘sccp_refcount_remove_obj’:
sccp_dllists.h:97:20: error: invalid type argument of ‘->’ (have ‘int’)
  typeof(__list_head->first) __list_next;        \
                    ^
sccp_dllists.h:107:41: note: in expansion of macro ‘SCCP_LIST_TRAVERSE_SAFE_BEGIN’
 #define SCCP_RWLIST_TRAVERSE_SAFE_BEGIN SCCP_LIST_TRAVERSE_SAFE_BEGIN
                                         ^
sccp_refcount.c:391:3: note: in expansion of macro ‘SCCP_RWLIST_TRAVERSE_SAFE_BEGIN’
   SCCP_RWLIST_TRAVERSE_SAFE_BEGIN(&(objects[hash])->refCountedObjects, obj, list) {
   ^
sccp_dllists.h:98:20: error: invalid type argument of ‘->’ (have ‘int’)
  typeof(__list_head->first) __list_prev = NULL;       \
                    ^
sccp_dllists.h:107:41: note: in expansion of macro ‘SCCP_LIST_TRAVERSE_SAFE_BEGIN’
 #define SCCP_RWLIST_TRAVERSE_SAFE_BEGIN SCCP_LIST_TRAVERSE_SAFE_BEGIN
                                         ^
sccp_refcount.c:391:3: note: in expansion of macro ‘SCCP_RWLIST_TRAVERSE_SAFE_BEGIN’
   SCCP_RWLIST_TRAVERSE_SAFE_BEGIN(&(objects[hash])->refCountedObjects, obj, list) {
   ^
sccp_dllists.h:99:20: error: invalid type argument of ‘->’ (have ‘int’)
  typeof(__list_head->first) __new_prev = NULL;       \
                    ^
sccp_dllists.h:107:41: note: in expansion of macro ‘SCCP_LIST_TRAVERSE_SAFE_BEGIN’
 #define SCCP_RWLIST_TRAVERSE_SAFE_BEGIN SCCP_LIST_TRAVERSE_SAFE_BEGIN
                                         ^
sccp_refcount.c:391:3: note: in expansion of macro ‘SCCP_RWLIST_TRAVERSE_SAFE_BEGIN’
   SCCP_RWLIST_TRAVERSE_SAFE_BEGIN(&(objects[hash])->refCountedObjects, obj, list) {
   ^
sccp_dllists.h:100:26: error: invalid type argument of ‘->’ (have ‘int’)
  for ((var) = __list_head->first, __new_prev = (var),      \
                          ^
sccp_dllists.h:107:41: note: in expansion of macro ‘SCCP_LIST_TRAVERSE_SAFE_BEGIN’
 #define SCCP_RWLIST_TRAVERSE_SAFE_BEGIN SCCP_LIST_TRAVERSE_SAFE_BEGIN
                                         ^
sccp_refcount.c:391:3: note: in expansion of macro ‘SCCP_RWLIST_TRAVERSE_SAFE_BEGIN’
   SCCP_RWLIST_TRAVERSE_SAFE_BEGIN(&(objects[hash])->refCountedObjects, obj, list) {
   ^
sccp_dllists.h:100:46: warning: assignment makes integer from pointer without a cast [enabled by default]
  for ((var) = __list_head->first, __new_prev = (var),      \
                                              ^
sccp_dllists.h:107:41: note: in expansion of macro ‘SCCP_LIST_TRAVERSE_SAFE_BEGIN’
 #define SCCP_RWLIST_TRAVERSE_SAFE_BEGIN SCCP_LIST_TRAVERSE_SAFE_BEGIN
                                         ^
sccp_refcount.c:391:3: note: in expansion of macro ‘SCCP_RWLIST_TRAVERSE_SAFE_BEGIN’
   SCCP_RWLIST_TRAVERSE_SAFE_BEGIN(&(objects[hash])->refCountedObjects, obj, list) {
   ^
sccp_dllists.h:100:33: warning: left-hand operand of comma expression has no effect [-Wunused-value]
  for ((var) = __list_head->first, __new_prev = (var),      \
                                 ^
sccp_dllists.h:107:41: note: in expansion of macro ‘SCCP_LIST_TRAVERSE_SAFE_BEGIN’
 #define SCCP_RWLIST_TRAVERSE_SAFE_BEGIN SCCP_LIST_TRAVERSE_SAFE_BEGIN
                                         ^
sccp_refcount.c:391:3: note: in expansion of macro ‘SCCP_RWLIST_TRAVERSE_SAFE_BEGIN’
   SCCP_RWLIST_TRAVERSE_SAFE_BEGIN(&(objects[hash])->refCountedObjects, obj, list) {
   ^
sccp_dllists.h:101:20: warning: assignment makes integer from pointer without a cast [enabled by default]
        __list_next = (var) ? (var)->field.next : NULL;      \
                    ^
sccp_dllists.h:107:41: note: in expansion of macro ‘SCCP_LIST_TRAVERSE_SAFE_BEGIN’
 #define SCCP_RWLIST_TRAVERSE_SAFE_BEGIN SCCP_LIST_TRAVERSE_SAFE_BEGIN
                                         ^
sccp_refcount.c:391:3: note: in expansion of macro ‘SCCP_RWLIST_TRAVERSE_SAFE_BEGIN’
   SCCP_RWLIST_TRAVERSE_SAFE_BEGIN(&(objects[hash])->refCountedObjects, obj, list) {
   ^
sccp_dllists.h:100:33: warning: value computed is not used [-Wunused-value]
  for ((var) = __list_head->first, __new_prev = (var),      \
                                 ^
sccp_dllists.h:107:41: note: in expansion of macro ‘SCCP_LIST_TRAVERSE_SAFE_BEGIN’
 #define SCCP_RWLIST_TRAVERSE_SAFE_BEGIN SCCP_LIST_TRAVERSE_SAFE_BEGIN
                                         ^
sccp_refcount.c:391:3: note: in expansion of macro ‘SCCP_RWLIST_TRAVERSE_SAFE_BEGIN’
   SCCP_RWLIST_TRAVERSE_SAFE_BEGIN(&(objects[hash])->refCountedObjects, obj, list) {
   ^
sccp_dllists.h:103:39: warning: assignment makes pointer from integer without a cast [enabled by default]
       __list_prev = __new_prev, (var) = __list_next,      \
                                       ^
sccp_dllists.h:107:41: note: in expansion of macro ‘SCCP_LIST_TRAVERSE_SAFE_BEGIN’
 #define SCCP_RWLIST_TRAVERSE_SAFE_BEGIN SCCP_LIST_TRAVERSE_SAFE_BEGIN
                                         ^
sccp_refcount.c:391:3: note: in expansion of macro ‘SCCP_RWLIST_TRAVERSE_SAFE_BEGIN’
   SCCP_RWLIST_TRAVERSE_SAFE_BEGIN(&(objects[hash])->refCountedObjects, obj, list) {
   ^
sccp_dllists.h:104:18: warning: assignment makes integer from pointer without a cast [enabled by default]
       __new_prev = (var),         \
                  ^
sccp_dllists.h:107:41: note: in expansion of macro ‘SCCP_LIST_TRAVERSE_SAFE_BEGIN’
 #define SCCP_RWLIST_TRAVERSE_SAFE_BEGIN SCCP_LIST_TRAVERSE_SAFE_BEGIN
                                         ^
sccp_refcount.c:391:3: note: in expansion of macro ‘SCCP_RWLIST_TRAVERSE_SAFE_BEGIN’
   SCCP_RWLIST_TRAVERSE_SAFE_BEGIN(&(objects[hash])->refCountedObjects, obj, list) {
   ^
sccp_dllists.h:105:19: warning: assignment makes integer from pointer without a cast [enabled by default]
       __list_next = (var) ? (var)->field.next : NULL      \
                   ^
sccp_dllists.h:107:41: note: in expansion of macro ‘SCCP_LIST_TRAVERSE_SAFE_BEGIN’
 #define SCCP_RWLIST_TRAVERSE_SAFE_BEGIN SCCP_LIST_TRAVERSE_SAFE_BEGIN
                                         ^
sccp_refcount.c:391:3: note: in expansion of macro ‘SCCP_RWLIST_TRAVERSE_SAFE_BEGIN’
   SCCP_RWLIST_TRAVERSE_SAFE_BEGIN(&(objects[hash])->refCountedObjects, obj, list) {
   ^
sccp_dllists.h:111:12: error: invalid type argument of ‘->’ (have ‘int’)
  __new_prev->field.next = NULL;         \
            ^
sccp_dllists.h:130:36: note: in expansion of macro ‘SCCP_LIST_REMOVE_CURRENT’
 #define SCCP_RWLIST_REMOVE_CURRENT SCCP_LIST_REMOVE_CURRENT
                                    ^
sccp_refcount.c:393:5: note: in expansion of macro ‘SCCP_RWLIST_REMOVE_CURRENT’
     SCCP_RWLIST_REMOVE_CURRENT(list);
     ^
sccp_dllists.h:112:12: error: invalid type argument of ‘->’ (have ‘int’)
  __new_prev->field.prev = NULL;         \
            ^
sccp_dllists.h:130:36: note: in expansion of macro ‘SCCP_LIST_REMOVE_CURRENT’
 #define SCCP_RWLIST_REMOVE_CURRENT SCCP_LIST_REMOVE_CURRENT
                                    ^
sccp_refcount.c:393:5: note: in expansion of macro ‘SCCP_RWLIST_REMOVE_CURRENT’
     SCCP_RWLIST_REMOVE_CURRENT(list);
     ^
sccp_dllists.h:116:14: warning: assignment makes integer from pointer without a cast [enabled by default]
   __new_prev = NULL;         \
              ^
sccp_dllists.h:130:36: note: in expansion of macro ‘SCCP_LIST_REMOVE_CURRENT’
 #define SCCP_RWLIST_REMOVE_CURRENT SCCP_LIST_REMOVE_CURRENT
                                    ^
sccp_refcount.c:393:5: note: in expansion of macro ‘SCCP_RWLIST_REMOVE_CURRENT’
     SCCP_RWLIST_REMOVE_CURRENT(list);
     ^
sccp_dllists.h:119:15: error: invalid type argument of ‘->’ (have ‘int’)
    __list_next->field.prev = __list_prev;      \
               ^
sccp_dllists.h:130:36: note: in expansion of macro ‘SCCP_LIST_REMOVE_CURRENT’
 #define SCCP_RWLIST_REMOVE_CURRENT SCCP_LIST_REMOVE_CURRENT
                                    ^
sccp_refcount.c:393:5: note: in expansion of macro ‘SCCP_RWLIST_REMOVE_CURRENT’
     SCCP_RWLIST_REMOVE_CURRENT(list);
     ^
sccp_dllists.h:120:14: error: invalid type argument of ‘->’ (have ‘int’)
   __list_prev->field.next = __list_next;       \
              ^
sccp_dllists.h:130:36: note: in expansion of macro ‘SCCP_LIST_REMOVE_CURRENT’
 #define SCCP_RWLIST_REMOVE_CURRENT SCCP_LIST_REMOVE_CURRENT
                                    ^
sccp_refcount.c:393:5: note: in expansion of macro ‘SCCP_RWLIST_REMOVE_CURRENT’
     SCCP_RWLIST_REMOVE_CURRENT(list);
     ^
sccp_dllists.h:122:14: error: invalid type argument of ‘->’ (have ‘int’)
   __list_head->first = __list_next;       \
              ^
sccp_dllists.h:130:36: note: in expansion of macro ‘SCCP_LIST_REMOVE_CURRENT’
 #define SCCP_RWLIST_REMOVE_CURRENT SCCP_LIST_REMOVE_CURRENT
                                    ^
sccp_refcount.c:393:5: note: in expansion of macro ‘SCCP_RWLIST_REMOVE_CURRENT’
     SCCP_RWLIST_REMOVE_CURRENT(list);
     ^
sccp_dllists.h:124:15: error: invalid type argument of ‘->’ (have ‘int’)
    __list_next->field.prev = NULL;       \
               ^
sccp_dllists.h:130:36: note: in expansion of macro ‘SCCP_LIST_REMOVE_CURRENT’
 #define SCCP_RWLIST_REMOVE_CURRENT SCCP_LIST_REMOVE_CURRENT
                                    ^
sccp_refcount.c:393:5: note: in expansion of macro ‘SCCP_RWLIST_REMOVE_CURRENT’
     SCCP_RWLIST_REMOVE_CURRENT(list);
     ^
sccp_dllists.h:127:14: error: invalid type argument of ‘->’ (have ‘int’)
   __list_head->last = __list_prev;        \
              ^
sccp_dllists.h:130:36: note: in expansion of macro ‘SCCP_LIST_REMOVE_CURRENT’
 #define SCCP_RWLIST_REMOVE_CURRENT SCCP_LIST_REMOVE_CURRENT
                                    ^
sccp_refcount.c:393:5: note: in expansion of macro ‘SCCP_RWLIST_REMOVE_CURRENT’
     SCCP_RWLIST_REMOVE_CURRENT(list);
     ^
sccp_dllists.h:128:13: error: invalid type argument of ‘->’ (have ‘int’)
  __list_head->size--;           \
             ^
sccp_dllists.h:130:36: note: in expansion of macro ‘SCCP_LIST_REMOVE_CURRENT’
 #define SCCP_RWLIST_REMOVE_CURRENT SCCP_LIST_REMOVE_CURRENT
                                    ^
sccp_refcount.c:393:5: note: in expansion of macro ‘SCCP_RWLIST_REMOVE_CURRENT’
     SCCP_RWLIST_REMOVE_CURRENT(list);
     ^
sccp_refcount.c: At top level:
sccp_refcount.c:111:4: warning: ‘objects’ defined but not used [-Wunused-variable]
 } *objects[SCCP_HASH_PRIME];           //!< objects hash table
    ^
make[3]: *** [libsccp_la-sccp_refcount.lo] Error 1
make[3]: Leaving directory `/usr/src/chan-sccp_develop/src'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/usr/src/chan-sccp_develop/src'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/usr/src/chan-sccp_develop/src'
make: *** [all-recursive] Error 1

**chan-sccp version:** 4.3.0_develop_r1812b49

**asterisk version:** 13.13.1

**Addition / Optional Information:**

- Platform:
  Operating System : Linux
          Kernel : 3.10.0-514.6.1.el7.x86_64
    Architecture : x86_64
Asterisk Version : 11300 / 113
  Asterisk Repos : TRUNK
      Build user : root
         Version : 4.3.0_develop_r1812b49
Compiler Version : 4.8.5
              CC : gcc
             CPP : gcc -E
         HOST_CC : gcc

**Comment by dkgroot** [comment]
@jozzus 

You need to specify a size for the hash table, so --with-hash-size=xxxx. You only need to change this value if you have a high(er) number (100+) of phones connecting to the server. And if you do want ot change the size, the value needs to be a prime number.

BTW: You should not have to set the --with-astmoddir in most cases. Normally it is automatically detected and/or retrieved from /etc/asterisk/asterisk.conf. Note: some older asterisk binary packages were delivered with a broken asterisk.conf file (They used '=' instead of '=>' for the paths), the configure script will detect and report this. You need to fix this file manually before recompiling. Once the file is repaired you can re-run configure. The --with-astmoddir parameter was mostly added for package maintainers.

Can you replace
./configure --enable-conference --enable-distributed-devicestate --with-astmoddir=/usr/lib64/asterisk/modules/ --enable-advanced-functions --with-hash-size

With
./configure --enable-conference --enable-distributed-devicestate --enable-advanced-functions --with-hash-size=3001

**Comment by dkgroot** [comment]
Committed Revision: aed782f
Which will check the value supplied. Will generate error and stop configure if false.
