### ISSUE TITLE
Transfer on 6901 (one way audio with transfer recipient)

### ISSUE THREAD

**Issue by dkgroot** [chan-sccp/chan-sccp#381]
Diogo reported issues when trying to transfer a call using a 6901

Issues:
1. First issue, not being able to dial the transfer recipient
  Analysis: was caused by focus shifting back to transfered
  Fixed in source. Was caused by:
    - selectsoftkeys to the wrong callid.
    - missing
      ```xml
      <vendorConfig>
      <autoCallSelect>0</autoCallSelect>
      </vendorConfig>
      ```
   FIXED
2.  one way audio with the transfer recipient
  Analysis: the start media transmission ack message is missing the passThruPartId is missing on the second call. See below
   FIXED

3. How to cancel a transfer in progress
    CHANGES COMMITTED / Waiting for results

Note: 6901 phones do not have a transfer key, they use hookflash to instantiate the transfer process
BTW: Call was hungup to complete the transfer (not sure if transfer_on_hangup is set).

```
[2017-02-27 19:42:02] NOTICE[29647]: sccp_session.c:989 sccp_session_send2: SEP3C5EC30C4C4B: Send Message: Start Media Transmission(0x008A) 136 bytes length
 SCCP: packet hex dump:
 00000000 - 88 00 00 00 14 00 00 00  8A 00 00 00 15 00 00 00  - ................
 00000010 - EA FF FF FF 00 00 00 00  0A 01 02 23 00 00 00 00  - ...........#....
 00000020 - 00 00 00 00 00 00 00 00  B4 28 00 00 14 00 00 00  - .........(......
 00000030 - 02 00 00 00 B8 00 00 00  00 00 00 00 00 00 00 00  - ................
 00000040 - 00 00 00 00 15 00 00 00  00 00 00 00 00 00 00 00  - ................
 00000050 - 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  - ................
 00000060 - 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  - ................
 00000070 - 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  - ................
 00000080 - 65 00 00 00 0A 00 00 00  00 00 00 00 00 00 00 00  - e...............
    -- SEP3C5EC30C4C4B: send callInfo on SCCP/22-00000015 with lineInstance: 1
    -- SEP3C5EC30C4C4B: >> Send message Stop Tone Message
[2017-02-27 19:42:02] NOTICE[29647]: sccp_session.c:989 sccp_session_send2: SEP3C5EC30C4C4B: Send Message: Stop Tone Message(0x0083) 16 bytes length
 SCCP: packet hex dump:
 00000000 - 10 00 00 00 14 00 00 00  83 00 00 00 01 00 00 00  - ................
 00000010 - 15 00 00 00 00 00 00 00                           - ........
    -- SEP3C5EC30C4C4B: >> Got message Start Media Transmission Acknowledge (0x154)
[2017-02-27 19:42:02] NOTICE[29647]: sccp_actions.c:121 check_session_message_device: SEP3C5EC30C4C4B: SCCP Handle Message: Start Media Transmission Acknowledge(0x0154) 52 bytes length
 SCCP: packet hex dump:
 00000000 - 34 00 00 00 14 00 00 00  54 01 00 00 00 00 00 00  - 4.......T.......
 00000010 - 00 00 00 00 15 00 00 00  00 00 00 00 0A 01 02 2C  - ...............,
 00000020 - 00 00 00 00 00 00 00 00  00 00 00 00 B4 28 00 00  - .............(..
 00000030 - 00 00 00 00 00 00 00 00  00 00 00 00              - ............
    -- SEP3C5EC30C4C4B: Getting the active channel on device.
[2017-02-27 19:42:02] WARNING[29647]: sccp_actions.c:3511 handle_startmediatransmission_ack: SEP3C5EC30C4C4B: Channel with passthrupartyid 0 / callid 0 / callid1 21 not found, please report this to developer
```

**Comment by dkgroot** [comment]
Related #335

**Comment by dkgroot** [comment]
Changes:
- Added exception in startMediaTransmissionAck Handling for 6901
- Close Port during HOLD
- Added commented section about protocol 20 startmediatransmission and 69XX phones.

**Comment by dkgroot** [comment]
Previous changes works. Transfer is now working

There was still an issue, namely cancelling a transfer in progress. According to the cisco manual the user should press the Line Button (strange but ok). I though it would make more sense to have the user press the hold key instead. But maybe that last change is not what the users wants. Maybe they want to consult back an forth between both transfer parties (need to test/check/not even sure if that would work on a 6901).

Changes:
-Fix: allow single line device (like 6901) to cancel transfer by pressing the line key (see cisco manual for 6901)
-Enh: allow single line device (like 6901) to cancel transfer by pressing the hold key on the transferer channel

**Comment by FilipeDiogo** [comment]
With revision 7725952 it appears that the transfer is working and the resume for the 1st call on hold is working to! no more problems with no audio.... 

👍

**Comment by dkgroot** [comment]
Thanks for the update. Will merge this issues/381 branch back into develop tomorrow, after reviewing the changes and maybe clean up.

Thanks for helping out with all the tests.

@voipasteriskguy can you verify that these changes also work for issue #335 ?

**Comment by dkgroot** [comment]
@FilipeDiogo :
The issues/381 branch has been closed and merged into the develop branch. Please do:
```
git checkout develop
git pull
make && make reload
```
To get back to the 'develop' branch
