### ISSUE TITLE
8945 - Call forwarding disable does not correctly update GUI

### ISSUE THREAD

**Issue by bcdaus** [chan-sccp/chan-sccp#403]
When disabling call forwarding on 8945, the Phone GUI does not correctly reflect the call forwarding status until a menu pop up is opened on the phone.

**Reproduction Steps:**
Enable call forwarding to know extension - gui will show forwarding icon and text
![forwarding active](https://cloud.githubusercontent.com/assets/2332284/25553340/b6831f3e-2cf3-11e7-8e5d-2984b08beedd.png)
Press Forward Off

**Expected behavior:**
Phone line icon will remove forarding notification.  Forward OFF button text will return to Forward All.  Forwarding text in header will be cleared.

**Observed behavior:**
Phone Icon removes forwarding Icon.
Button remains as Forward Off text
Header retains forwarding info
![forward off issue](https://cloud.githubusercontent.com/assets/2332284/25553354/567727ba-2cf4-11e7-80c6-f177393d9c57.png)

Bringing up an on screen menu (say the Quick Dials option and then closing it clears the button name and header as expected.
![forward off popup](https://cloud.githubusercontent.com/assets/2332284/25553358/7ac86e62-2cf4-11e7-99a9-038de0d92044.png)
![forward off after popup](https://cloud.githubusercontent.com/assets/2332284/25553361/80190a2a-2cf4-11e7-8b06-7ec1544cda17.png)

CLI shows correct clearing of forwarding status
```
-     -- SEP6CFA897380F4: Call Forward disabled on line 98030
    --     -- SEP6CFA897380F4: db clear SCCP/SEP6CFA897380F4/98030
```

**chan-sccp version:**
Skinny Client Control Protocol (SCCP). Release: 4.3.0 develop - 46f48e9M (built by 'root' on '2016-08-28 09:20:03 UTC')

**asterisk version**: (include revision and/or branch if relevant)
Asterisk 13.7.2

**Addition / Optional Information:**
- Problem started happening recently, didn't happen in an older version of Chan-SCCP: Not Sure
- Problem can be reliably reproduced, doesn't happen randomly: Yes
- Platform:
Incredible PBX 13-12.2
Kernel Version - 2.6.32-573.12.1.el6.i686 (SMP) i686
Distro Name - Icon Scientific Linux release 6.7 (Carbon)
CPU - Dual Core Intel(R) Celeron(R) 2955U @ 1.40GHz (ChromeBox)

**Phone Firmware**
Image Version : SCCP894x.9-4-2SR3-1
Also happened on Image 9-4-2-SR2-2

**Comment by dkgroot** [comment]
@bcdaus 
Sorry that it took some time to get around to looking at this issue. The handling of the skinny protocol on 69xx and 89xx phones differes quite a bit from what we were used to when developing for the 79xx series. The 89xx phones do seem to expect some events to happen in a pre-specified order, which we have not been able to find out (yet). If you do have access to a cucm machine, it would be very helpfull if you could capture some of this information (via tcpdump/wireshark).

**Comment by dkgroot** [comment]
I can reproduce the issue now. Have not had time to look into a possible solution just yet

**Comment by dkgroot** [comment]
***Git***
_Checkout this temporary branch_
```
git pull
git fetch -a
git branch
git checkout issues/403
./configure [....]
make -j4 && make install && make reload
```

_move back to develop afterwards:_
```
git checkout develop
```
