### ISSUE TITLE
DTMF not working with asterisk-15.2 past revision asterisk:86c75af860

### ISSUE THREAD

**Issue by dkgroot** [chan-sccp/chan-sccp#425]
When using newer asterisk revisons (past: 
https://github.com/asterisk/asterisk/commit/86c75af8600464e6f8aa326ba89006410ac0dd6e
) There is an issue with sending DTMF (rfc2833)

Working on a fix.

Issue was reported by Frederic Steinfels

**Comment by dkgroot** [comment]
@frederic
Pushed a new branch 'issues/425'.
Would you mind testing it ? 
```
git checkout issues/425
make -j2
make reload
```

**Comment by noppel** [comment]
It works, thanks a lot
