### ISSUE TITLE
FreePBX 14 Asterisk v13.9.1

### ISSUE THREAD

**Issue by kbtang88** [chan-sccp/chan-sccp#427]
does this work with freepbx 14 asterisk 13.9.1 and can this run both on sip and sccp? i have cisco phone CP-7925ex?

**Comment by dkgroot** [comment]
@kbtang88 
Yes chan-sccp can be compiled against asterisk-13.9.1 and it will run/work with freepbx. You can run both sip and sccp channel drivers side by side. Phones can only run one protocol as a time (and you need to change the firmware of the phone to do this). The 7925 is supported.

There is a module for [FreePBX created by Alex](https://github.com/PhantomVl/sccp_manager)
Please checkout our [wiki](https://github.com/chan-sccp/chan-sccp/wiki) for more information, and [chan-sccp with FreePBX page](https://github.com/chan-sccp/chan-sccp/wiki/FreePBX) in particular.
