### ISSUE TITLE
warning in sccp_refcount.c (commit 1becc03)

### ISSUE THREAD

**Issue by hhornung** [chan-sccp/chan-sccp#443]
asterisk-version 13.24.1

  CC       libsccp_la-sccp_refcount.lo
In file included from common.h:43:0,
                 from sccp_refcount.c:41:
sccp_refcount.c: In function ‘sccp_refcount_find_obj’:
define.h:261:55: warning: initialization discards ‘const’ qualifier from pointer target type
         const typeof( ((type *)0)->member ) *__mptr = (ptr);    \
                                                                                      ^
sccp_refcount.c:346:26: note: in expansion of macro ‘container_of’
  RefCountedObject *obj = container_of(ptr, RefCountedObject, data);
                                            ^

**Comment by dkgroot** [comment]
@hhornung Thanks for reporting this slight regression, trying to figure out the best way to fix this one :-)
