### ISSUE TITLE
ConfList: initiator name replaced by conference name

### ISSUE THREAD

**Issue by darkponay** [chan-sccp/chan-sccp#454]
Hi!

A little bug seems to happen with the conflist, like in the screenshot below :
![screenshot](https://user-images.githubusercontent.com/18644554/54038228-4c3b6d00-41c0-11e9-81ca-97ca02244b9c.png)

As you can see, the initiator name is replaced by "Conference 101". Hopefully everything works, it is just a problem in displaying the name. All the functions work properly.

Changing Asterisk or chan-sccp version didn't change anything.

**Comment by dkgroot** [comment]
@darkponay 
Can you give issue/454 a try please
Merci bien !

**Comment by darkponay** [comment]
Hello!
For the moment, it seems perfect, I tried basic 2 members and 3 members conference, some hold/resume operations, promote as moderator and demote, and it is still the right name shown for the initiator!

**Comment by dkgroot** [comment]
Thanks for reporting the issue and testing the result. Solution has been merged !
